name: environment secrets and vars
on: push 

env: 
  WF_ENV: Available to all jobs                       # wf level var
  WF_ENV_ENCRYP: ${{ secrets.WF_ENV_ENCRYP }}         # wf level var with env secret

jobs: 
  log-env:
    runs-on: ubuntu-latest
    environment: dev
    env:
      JOB_ENV: Available to all steps in log-env jobs # job level var
    steps:
      - name: Log ENV Variables 
        env: 
          STEP_ENV: Available to only this step       # step level var
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "WF_ENV_ENCRYP: ${WF_ENV_ENCRYP}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
  log-default-env: 
    runs-on: ubuntu-latest
    steps:
      - name: Default ENV Variables 
        run: |
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "WF_ENV: ${WF_ENV}"
          echo "WF_ENV_ENCRYP: ${WF_ENV_ENCRYP}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"